### ISSUE TITLE
Issues with v5.0.10

### ISSUE THREAD

**Issue by rjbungay** [petergridge/irrigation_V5#3]
Hi Peter
A couple of small issues I have found with v5.0.10.
1. The Zone timer is no longer working properly, it just shows 0:00:00 all the way through the cycle and then returns to "Run zone" at the end of the cycle.
2. The "Last ran" display at the bottom of the card doesn't update.
Regards
Richard

**Comment by petergridge** [comment]
Hi Richard,

Did you upgrade the custom card? there was a breaking change on the card requirement because of the changed naming standard for the helpers.

**Comment by rjbungay** [comment]
As far as I know I successfully updated the card. I copied the new js file and added the new local repository with a v2 at the end following your instructions.

**Comment by rjbungay** [comment]
Is there a way to verify the card version?

**Comment by rjbungay** [comment]
Peter
I just updated the card via HACS a well now that you have released it. Still the same. The zone switch turns on and goes to yellow icon and the actual relay turns on and off correctly. However, the timer just shows 0:00:00 all the time then returns to run zone at the end of the cycle. Last run still doesn't update.

**Comment by petergridge** [comment]
That is really odd, I have just reinstalled both using HACS and it is doing it's job.
can you delete your __pycache__ directory , refresh the browser etc.

Then when it is running can you look at the attributes of the switch, using the developer tools. to see if they are updating just so I can determine if it is the custom control or the card.

**Comment by rjbungay** [comment]
Hi Peter
OK, deleted the custom card completely, deleted pycache, reinstalled the card from HACS.
Still the same, here are screenshots with morning running.
![image](https://user-images.githubusercontent.com/72338572/187883703-02eda595-f325-4c2e-b2a6-2e71ea7ca3d5.png)
![image](https://user-images.githubusercontent.com/72338572/187884066-4e458a77-f4b5-4175-a8a7-1694a6014c62.png)
As you can see the counter is running on the switch attributes.
There are two last ran attributes, neither of which show the correct date.
Hope this helps.
Cheers Richard

**Comment by petergridge** [comment]
The new version would have reset the last ran data, can you let start based on the time and let it run until it is complete to see if the data updates.

Can you downgrade back to the last version, I am off holidays next week so may not get it fixed before I go. Sorry.

**Comment by rjbungay** [comment]
This is my current yaml file
[irrigation.txt](https://github.com/petergridge/irrigation_V5/files/9468806/irrigation.txt)

**Comment by rjbungay** [comment]
Peter
The program still runs correctly, it is just the custom card that is not showing the right values.
So no need to downgrade 
Cheers Richard

**Comment by petergridge** [comment]
you can try to clear the browser cache, it's a pain but may make the difference

**Comment by craigueh** [comment]
I'm having the same issue and I think it's to do with the way the input_number helpers are created. If I go to Settings->Devices->Helpers and look at any of the auto-created input_numbers, moving the slider doesn't change the number or have any additional attributes but if I manually create a new test input_number and set the range from 0-100 then adjusting the slider correctly changes the number accordingly.
I presume if the auto input_numbers stay at the default value regardless of the slider position then the corresponding counter has no starting point and stays at 00:00. Just a guess though...

**Comment by petergridge** [comment]
Thanks for the heads up, please use version 8 or 9 with the matching custom card for the time being. I will be out of action for the month or two, but am working on a version that is set up through the UI, my major issue is the automated helpers so I may roll back that change to make this version more robust. I still think it a valuable feature but so far it is causing more issues than I expected. Nothing ventured, nothing gained though. I should have marked version 5 as a BETA. It's great to get feedback from users though. I have no idea how many users there are of this application.

**Comment by rjbungay** [comment]
Hi Peter
I think the issue is probably your entity naming. As you can see in my previous screenshot "morning_program_plant_water_remaing" is counting down correctly. I suspect you are displaying the other attribute "morning_plant_water_remaining" which just stays at 0:00:00.
I’m not sure about the last ran, you have 2 attributes for that, neither of which are getting updated.
Regards Richard

**Comment by petergridge** [comment]
Thanks Richard, I am sure it was introduced when I moved from naming the attributes and generated helpers based on alias to naming based on the the actual name. 

At the moment I am abandoning the automated generation of helpers in favour of the configuration via the UI as this is the best path to getting the component accepted into HA Core.

From the testing I have done the method I am using is not sustainable, if another component tried to use the same method there are a lot of issues. So I have decided to stick to the core methods and not get to adventurous.

Some of the advantages of the new path are you can create and modify the component config without rebooting (with the auto helpers a reboot was still required) so with the helpers created via the UI and the component created via the UI I think that is better.

I have a working early BETA but it still has some work to do to migrate the yaml from v4 and a few assorted gremlins. It should be compatible with the V4 custom card.

I am off on a months adventure through Europe this week so will not be looking at the code for a while. If I have a chance I will put a version 5.1.0 Beta up with the new version before I leave. I doubt I will have it fully tested with the Custom Card by then though.

**Comment by rjbungay** [comment]
Hi Peter

Enjoy your holiday in this side of the planet. 

Cheers
Richard

**Comment by petergridge** [comment]
Hi, I have created pre release versions v5.1.**  for the custom component and card. The documentation is not updated but I am sure you can wing it. You will need to select the 'show beta versions' in the download screen of HACS to see these versions.

This version has:
* V4 based configuration, it should import your configuration to the config flow. If you get errors you may need to delete a couple of the options, like friendly name or icon. These can be maintained on the entity once created in the config flow
* The card is a behaving a little off at the moment but I have run out of time.
* If you have speak another language I would really appreciate if you could look at creating a language file for the configurator.
* Functionally this version should behave the same, but there have been some improvements to the responsiveness.

Cheers
Pete

**Comment by rjbungay** [comment]
Hi Peter
I have tried the new v5.1 but it is failing to load. I get the following in the log files.
Invalid config for [switch.irrigationprogram]: Entity ID Enable zone is an invalid entity ID for dictionary value @ data['switches']['afternoon']['zones'][0]['enable_zone']. Got 'Enable zone' Entity ID Enable zone is an invalid entity ID for dictionary value @ data['switches']['morning']['zones'][0]['enable_zone']. Got 'Enable zone' Entity ID Repeat is an invalid entity ID for dictionary value @ data['switches']['afternoon']['zones'][0]['repeat']. Got 'Repeat' Entity ID Repeat is an invalid entity ID for dictionary value @ data['switches']['morning']['zones'][0]['repeat']. Got 'Repeat' Entity ID Wait is an invalid entity ID for dictionary value @ data['switches']['afternoon']['zones'][0]['wait']. Got 'Wait' Entity ID Wait is an invalid entity ID for dictionary value @ data['switches']['morning']['zones'][0]['wait']. Got 'Wait' Entity ID Water is an invalid entity ID for dictionary value @ data['switches']['afternoon']['zones'][0]['water']. Got 'Water' Entity ID Water is an invalid entity ID for dictionary value @ data['switches']['morning']['zones'][0]['water']. Got 'Water'. (See /config/packages/irrigation.yaml, line 7). Please check the docs at https://github.com/petergridge/irrigation_v5

Line 7 in my yaml file is the "switch" definition.
    sensor:
      - platform: time_date
        display_options:
          - 'time'
          - 'date'

    switch:
      - platform: irrigationprogram
        switches: 
          morning:
            irrigation_on: Enable irrigation
#            friendly_name: Morning Program
            start_time: Start time
            show_config: Show configuration
            run_freq: input_select.irrigation_freq
            zones:
              - zone: switch.plant_water
                name: Pot Plants
#                zone_group: Zone group
                water: Water
                wait: Wait
                repeat: Repeat
                rain_sensor: binary_sensor.raining
                enable_zone: Enable zone
                water_adjustment: sensor.rainfactor

**Comment by petergridge** [comment]
Hi, 
This will only import v4 yaml where the objects are fully specified, I should put more defensive programming in so it does not fail on importing 'bad' yaml. I'll add that to the todo list.

I would recommend removing your yaml (save it first) and use the config flow to redefine it from scratch.

**Comment by craigueh** [comment]
Thanks for your hard work on this. I just updated to 5.1.8 and all seems to be working well with yaml removed. I noticed on the previous version any change to a zone required a re-run of the program options config, not sure if that's the case with this version. Haven't tested that yet. Will report any issues if i find them.

On a side note, does the new Homeassistant scheduler function in the latest version make things any easier for this integration or do you intend to use it at all?

**Comment by petergridge** [comment]
No restart required now, one of the benefits of the config flow model. It was a mission getting the update functionality to work, gota love trial and error and a few educated guesses.

This control implements the equivalent of a template sensor that is how it starts based on the attributes that are provided. So no real need to integrate with another component. I have not looked closely at the new functionality though so I will do some research before I make a decision.

**Comment by petergridge** [comment]
If you have another language other than English it would be great if you could prepare a translation. Just copy the en.json and do your thing.

**Comment by petergridge** [comment]
@rjbungay  I have fixed the validation of the YAML before importing so there is better error handling if the YAML does not check out, I still had the v5 schema.

**Comment by rjbungay** [comment]
Hi Peter
Not sure where I'm going wrong here? I've tried loading the latest version both with a v4 format yaml and no yaml but I can't get it to configure. I get the following error:-

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/irrigationprogram/__init__.py", line 76, in async_setup
    for domain in platforms:
TypeError: 'NoneType' object is not iterable

I also get a message saying no zone group entities found, not sure if this is related?
![image](https://user-images.githubusercontent.com/72338572/189207057-be5e7bed-9ca7-447d-8f78-ea6b53a40008.png)

Any pointers as to where I'm going wrong would be appreciated?

Sorry, I don't have a second language.

Hope you have a good holiday.
Richard

**Comment by petergridge** [comment]
Hi Richard, 

The no matching entities is simply that there are no input.text helpers to select for this field. It is not an error.

I did manage to recreate your error, you appear to have no switch entities defined at all! I have added some defensive coding for this (V5.1.10). I would not have found that testing in a million years! one more to add to my list.

I am off to the airport soon, I intend to enjoy every minute of the break, a laptop free zone for a month!. I will get withdrawal symptoms. No HA dev environment on my phone!

Pete

**Comment by rjbungay** [comment]
Hi Pete 

Quick update. The latest version seems to be running fine with no problems. 
Water adjustment is working as expected, "raining" stops the watering altogether, last ran working correctly etc. 
thank you for the integration and all your support getting it up and running. 
Cheers Richard
