### ISSUE TITLE
Cant get component to configure correctly.

### ISSUE THREAD

**Issue by craigueh** [petergridge/irrigation_V5#6]
I had this working great with two programs and four zones, all was working well and at some point over the winter something was updated and the component failed to load but i never noticed until recently. The error in the logs is about swith or attributes:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/irrigationprogram/__init__.py", line 37, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, (Platform.SWITCH,))
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Nothing changed with the switches (esphome relays) but it no longer loads the component. I tried re-running the configuration wizard several times and eventualy deleted everything and reinstalled and configured minimal options with just one zone and minimum required switch and runtime options but it still fails to load with the above error.

Any idea where to go from here?

**Comment by petergridge** [comment]
Hi,

What version of the Irrigation Program and HA do you have installed? 

There have been changes on the HA side that deprecated some start up methods and the new Irrigation Program version is using the latest model.

If you are not at the latest version of both HA and the Irrigation Program can you update and let me know the result

**Comment by petergridge** [comment]
I just noticed you are looking at an older repository.

I created a new on when released to HACS https://github.com/petergridge/Irrigation-V5.

I will add a note to this repository to redirect other.

**Comment by craigueh** [comment]
Hi Peter

I’m using version 5.1.15, I presumed this was the latest?

**Comment by petergridge** [comment]
Hi, Bad comms on my behalf, I had to rename the archive when I published on HACS and did not put a notification up on the original archives.

5.2.6 is the latest version for the control 5.2.7 will be out in a few days, also a new version of the Card will be released with 5.2.7, from what I can tell we are at a 1000 users of the control now.

Use this link https://github.com/petergridge/Irrigation-V5 or search for irrigation program in HACS for the latest release.

**Comment by craigueh** [comment]
Yaay. That worked. The repos looked the same but clearly there was a difference. I’m up to 5.2.6 now and all is working again.  
Thank you.

**Comment by petergridge** [comment]
I am just coming off my watering season, I get a lot more requests this time of year as the northern hemisphere starts watering. Every time I think there couldn't be any more variations (or bugs) there are more requests.

I hope you have a nice summer.
